return {
  -- NvCheatsheet for easy keymap viewing
  {
    'smartinellimarco/nvcheatsheet.nvim',
    event = 'VeryLazy',
    opts = {
      header = {
        "██╗  ██╗██╗ ██████╗██╗  ██╗███████╗████████╗ █████╗ ██████╗ ████████╗",
        "██║ ██╔╝██║██╔════╝██║ ██╔╝██╔════╝╚══██╔══╝██╔══██╗██╔══██╗╚══██╔══╝",
        "█████╔╝ ██║██║     █████╔╝ ███████╗   ██║   ███████║██████╔╝   ██║   ",
        "██╔═██╗ ██║██║     ██╔═██╗ ╚════██║   ██║   ██╔══██║██╔══██╗   ██║   ",
        "██║  ██╗██║╚██████╗██║  ██╗███████║   ██║   ██║  ██║██║  ██║   ██║   ",
        "╚═╝  ╚═╝╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ",
        "",
        "                     Neovim Kickstart Configuration",
        "",
      },
      keymaps = {
        ['Leader Key'] = {
          { 'Leader key = Space', '<Space>' },
        },
        ['File Operations'] = {
          { 'Smart Find Files', '<leader><space>' },
          { 'Find Files', '<leader>ff' },
          { 'Git Files', '<leader>fg' },
          { 'Recent Files', '<leader>fr' },
          { 'Find Config Files', '<leader>fc' },
          { 'Buffers', '<leader>fb' },
          { 'Delete Buffer', '<leader>bd' },
          { 'Rename File', '<leader>cR' },
        },
        ['Search Operations'] = {
          { 'Grep', '<leader>sg' },
          { 'Current Word', '<leader>sw' },
          { 'Buffer Lines', '<leader>sb' },
          { 'Open Buffers', '<leader>sB' },
          { 'Command History', '<leader>sc' },
          { 'Commands', '<leader>sC' },
          { 'Registers', '<leader>s"' },
          { 'Autocmds', '<leader>sa' },
          { 'Diagnostics', '<leader>sd' },
          { 'Buffer Diagnostics', '<leader>sD' },
          { 'Help Pages', '<leader>sh' },
          { 'Highlight Groups', '<leader>sH' },
          { 'Icons', '<leader>si' },
          { 'Jumps', '<leader>sj' },
          { 'Keymaps', '<leader>sk' },
          { 'Location List', '<leader>sl' },
          { 'Marks', '<leader>sm' },
          { 'Man Pages', '<leader>sM' },
          { 'Pickers', '<leader>sp' },
          { 'Quickfix List', '<leader>sq' },
          { 'Resume', '<leader>sR' },
          { 'Todo Comments', '<leader>st' },
          { 'Tmux Sessions', '<leader>sx' },
          { 'Undo History', '<leader>su' },
          { 'Yank History', '<leader>p' },
        },
        ['Git Operations'] = {
          { 'Lazygit', '<leader>gg' },
          { 'Git Browse', '<leader>gw' },
          { 'Git Branches', '<leader>gb' },
          { 'Git Log', '<leader>gl' },
          { 'Git Log (Current Line)', '<leader>gL' },
          { 'Git Status', '<leader>gs' },
          { 'Git Stash', '<leader>gS' },
          { 'Git Diff (Hunks)', '<leader>gd' },
          { 'Git Log (Current File)', '<leader>gf' },
        },
        ['LSP Operations'] = {
          { 'Goto Definition', 'gd' },
          { 'Goto Declaration', 'gD' },
          { 'Goto References', 'gr' },
          { 'Goto Implementation', 'gI' },
          { 'Type Definition', '<leader>D' },
          { 'Document Symbols', '<leader>cs' },
          { 'Workspace Symbols', '<leader>cS' },
          { 'Rename', '<leader>cr' },
          { 'Code Action', '<leader>ca' },
          { 'Source Action', '<leader>cA' },
          { 'Line Diagnostics', '<leader>cd' },
          { 'Format Document', '<leader>cf' },
          { 'Format Injected Langs', '<leader>cF' },
          { 'Lint Buffer', '<leader>cl' },
          { 'Rename File', '<leader>cR' },
          { 'LSP Info', '<leader>L' },
          { 'Toggle Inlay Hints', '<leader>th' },
        },
        ['Debug Operations (DAP)'] = {
          { 'Continue/Start', '<leader>dc' },
          { 'Run with Args', '<leader>da' },
          { 'Toggle Breakpoint', '<leader>db' },
          { 'Breakpoint Condition', '<leader>dB' },
          { 'Run to Cursor', '<leader>dC' },
          { 'Step Into', '<leader>di' },
          { 'Step Over', '<leader>do' },
          { 'Step Out', '<leader>dO' },
          { 'Up Frame', '<leader>dk' },
          { 'Down Frame', '<leader>dj' },
          { 'Toggle REPL', '<leader>dr' },
          { 'Run Last', '<leader>dl' },
          { 'Pause', '<leader>dp' },
          { 'Terminate', '<leader>dt' },
          { 'Toggle DAP UI', '<leader>du' },
          { 'Widgets', '<leader>dw' },
          { 'Disconnect', '<leader>dd' },
        },
        ['Buffer Management'] = {
          { 'Delete Buffer', '<leader>bd' },
          { 'Delete Other Buffers', '<leader>bD' },
          { 'Delete All Buffers', '<leader>bl' },
          { 'Next Buffer', '<leader>bn' },
          { 'Prev Buffer', '<leader>bp' },
          { 'Reload Buffer', '<leader>br' },
          { 'Scratch Buffer', '<leader>bs' },
          { 'Select Scratch Buffer', '<leader>bS' },
          { 'Buffer Local Keymaps', '<leader>?' },
        },
        ['Plugin Management (Lazy)'] = {
          { 'Lazy Home', '<leader>l' },
          { 'Lazy Install', '<leader>li' },
          { 'Lazy Sync', '<leader>ls' },
          { 'Lazy Update', '<leader>lu' },
          { 'Lazy Clean', '<leader>lc' },
          { 'Lazy Check', '<leader>lC' },
          { 'Lazy Log', '<leader>ll' },
          { 'Lazy Restore', '<leader>lr' },
          { 'Lazy Clear', '<leader>lx' },
          { 'Lazy Profile', '<leader>lp' },
          { 'Lazy Debug', '<leader>ld' },
        },
        ['Diagnostics (Trouble)'] = {
          { 'Project Diagnostics', '<leader>xx' },
          { 'Buffer Diagnostics', '<leader>xX' },
          { 'Location List', '<leader>xL' },
          { 'Quickfix List', '<leader>xQ' },
          { 'Symbols', '<leader>cs' },
          { 'LSP References', '<leader>cl' },
          { 'Next Trouble', ']t' },
          { 'Prev Trouble', '[t' },
        },
        ['Flash Navigation'] = {
          { 'Flash Jump', 's' },
          { 'Flash Treesitter', 'S' },
          { 'Remote Flash', 'r' },
          { 'Treesitter Search', 'R' },
          { 'Toggle Flash in Search', '<C-s>' },
        },
        ['Testing (Neotest)'] = {
          { 'Run Nearest Test', '<leader>tr' },
          { 'Run File Tests', '<leader>tt' },
          { 'Run All Tests', '<leader>tT' },
          { 'Run Last Test', '<leader>tl' },
          { 'Test Summary', '<leader>ts' },
          { 'Test Output', '<leader>to' },
          { 'Test Output Panel', '<leader>tO' },
          { 'Stop Tests', '<leader>tS' },
          { 'Watch Tests', '<leader>tw' },
        },
        ['Debugging (DAP)'] = {
          { 'Start/Continue Debug', '<F5>' },
          { 'Step Into', '<F1>' },
          { 'Step Over', '<F2>' },
          { 'Step Out', '<F3>' },
          { 'Toggle Breakpoint', '<leader>b' },
          { 'Conditional Breakpoint', '<leader>B' },
          { 'Debug UI Toggle', '<F7>' },
        },
        ['Window Management'] = {
          { 'Resize Left', '<A-h>' },
          { 'Resize Down', '<A-j>' },
          { 'Resize Up', '<A-k>' },
          { 'Resize Right', '<A-l>' },
          { 'Move Cursor Left', '<C-h>' },
          { 'Move Cursor Down', '<C-j>' },
          { 'Move Cursor Up', '<C-k>' },
          { 'Move Cursor Right', '<C-l>' },
          { 'Window Hydra Mode', '<C-w><space>' },
        },
        ['Terminal'] = {
          { 'Toggle Terminal', '<C-/>' },
          { 'Toggle Terminal (alt)', '<C-_>' },
          { 'Exit Terminal Mode', '<Esc><Esc>' },
        },
        ['UI Toggles'] = {
          { 'Spelling', '<leader>us' },
          { 'Line Wrap', '<leader>uw' },
          { 'Line Numbers', '<leader>ul' },
          { 'Relative Numbers', '<leader>uL' },
          { 'Diagnostics', '<leader>ud' },
          { 'Dark/Light Background', '<leader>ub' },
          { 'Inlay Hints', '<leader>uh' },
          { 'Colorscheme', '<leader>uC' },
          { 'Dismiss Notifications', '<leader>un' },
        },
        ['Obsidian Notes'] = {
          { 'Open Note', '<leader>on' },
          { 'New Note', '<leader>oN' },
          { 'Open in Obsidian App', '<leader>oo' },
          { 'Today Note', '<leader>ot' },
          { 'Search Notes', '<leader>os' },
          { 'Quick Switch', '<leader>oq' },
          { 'Backlinks', '<leader>ob' },
          { 'Note Links', '<leader>ol' },
          { 'Tags', '<leader>oT' },
          { 'Rename Note', '<leader>or' },
          { 'Toggle Checkbox', '<leader>ch' },
          { 'Follow Link', 'gf' },
          { 'Smart Action', '<CR>' },
        },
        ['Workspaces'] = {
          { 'Find Workspaces', '<leader>fw' },
          { 'Add Workspace', '<leader>wa' },
          { 'Remove Workspace', '<leader>wr' },
        },
        ['Yank History (Yanky)'] = {
          { 'Enhanced Put After', 'p' },
          { 'Enhanced Put Before', 'P' },
          { 'Put After (keep cursor)', 'gp' },
          { 'Put Before (keep cursor)', 'gP' },
          { 'Next Yank in Ring', ']y' },
          { 'Prev Yank in Ring', '[y' },
          { 'Yank History Picker', '<leader>p' },
        },
        ['Recent Edits Navigation'] = {
          { 'Recently Edited Locations', '<leader>re' },
          { 'Next Recent Edit', ']e' },
          { 'Prev Recent Edit', '[e' },
        },
        ['Git Age Navigation'] = {
          { 'Next Change (≤1 day)', ']rd' },
          { 'Prev Change (≤1 day)', '[rd' },
          { 'Next Change (≤1 week)', ']rw' },
          { 'Prev Change (≤1 week)', '[rw' },
          { 'Next Change (≤1 month)', ']rm' },
          { 'Prev Change (≤1 month)', '[rm' },
        },
        ['Git Changes Navigation'] = {
          { 'Next Project Change', ']g' },
          { 'Prev Project Change', '[g' },
          { 'Open Project Changes (QF)', '<leader>gq' },
        },
        ['Misc'] = {
          { 'Command History', '<leader>:' },
          { 'Notification History', '<leader>n' },
          { 'Neovim News', '<leader>N' },
          { 'Buffer Keymaps', '<leader>?' },
          { 'Next Reference', ']]' },
          { 'Prev Reference', '[[' },
          { 'Reload Config', '<leader>R' },
        },
      },
    },
    config = function(_, opts)
      local nvcheatsheet = require('nvcheatsheet')
      nvcheatsheet.setup(opts)
      
      -- Set up toggle keybinding
      vim.keymap.set('n', '<leader>uc', function()
        nvcheatsheet.toggle()
      end, { desc = 'Toggle Cheatsheet' })

      -- Also bind to F1 for quick access
      vim.keymap.set('n', '<F1>', function()
        nvcheatsheet.toggle()
      end, { desc = 'Toggle Cheatsheet' })
    end,
  },
}